### PR TITLE
Add data for Tales game series entries

### PR DESCRIPTION
**Pull request by iamdanhart**

### CODE REVIEW

**Comment by euhidaman** [comment]
Please , do not add empty file.
At least, put some data in the file, in JSON format.

**Comment by iamdanhart** [comment]
I'm so sorry, I swear I had data in there... Will resolve...

**Comment by iamdanhart** [comment]
I think the file is in the PR now, I must have mistyped something when I was committing... Sorry again!

**Comment by euhidaman** [comment]
No worries !! Mistakes happen because we are humans !!

Anyway, thanks for contributing !!☺☺

**Pull request merged**
